spring.application.name=generation-worker

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:genflow}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:genflow123}

server.port=8081

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=genflow-group
spring.kafka.consumer.auto-offset-reset=earliest